Repository umee-network/peggo, pull requests merged in 2021-12, with the labels that each got.

#79 fix: Lock Solidity compiler version to 0.8.4
  solidity/contracts/CosmosToken.sol
  solidity/contracts/HashingTest.sol
  solidity/contracts/Peggy.sol
  solidity/contracts/TestERC20.sol
Labels: S:backport/v0.1.x

#83 perf: Send Ethereum claims msgs in batches instead of individual transactions
  Dockerfile
  cmd/peggo/orchestrator.go
  orchestrator/cosmos/broadcast.go
  orchestrator/cosmos/broadcast_test.go
  orchestrator/eth_event_watcher_test.go
  orchestrator/relayer/relayer.go
  orchestrator/relayer/valset_relaying.go
  test/e2e/e2e_setup_test.go
Labels: A:Automerge, S:backport/v0.1.x, T:Performance

#91 chore: Ran make solidity-wrappers
  solidity/wrappers/CosmosToken.sol/wrapper.go
  solidity/wrappers/HashingTest.sol/wrapper.go
  solidity/wrappers/Peggy.sol/wrapper.go
  solidity/wrappers/TestERC20.sol/wrapper.go
Labels: A:Automerge, S:backport/v0.1.x

#95 feat: support fee grants
  cmd/peggo/flags.go
  cmd/peggo/orchestrator.go
  orchestrator/cosmos/broadcast.go
Labels: S:backport/v0.1.x

#100 fix: Gas cost estimation is now used instead of hardcoded value
  orchestrator/ethereum/committer/committer.go
  orchestrator/ethereum/committer/eth_committer.go
  orchestrator/relayer/batch_relaying.go
  orchestrator/relayer/valset_relaying.go
Labels: S:backport/v0.1.x

#102 chore: add changelog
  CHANGELOG.md
Labels: S:backport/v0.1.x

#104 fix: Chunk claims messages
  CHANGELOG.md
  cmd/peggo/client/cosmos.go
  orchestrator/cosmos/broadcast.go
Labels: S:backport/v0.1.x

#105 feat: Add gas limit adjustment flag
  CHANGELOG.md
  cmd/peggo/flags.go
  cmd/peggo/orchestrator.go
  orchestrator/eth_event_watcher_test.go
  orchestrator/ethereum/committer/eth_committer.go
  orchestrator/ethereum/peggy/peggy_contract_test.go
  orchestrator/ethereum/peggy/pending_transactions_test.go
  orchestrator/ethereum/peggy/submit_batch_test.go
  orchestrator/ethereum/peggy/valset_update_test.go
  orchestrator/oracle_resync_test.go
  orchestrator/relayer/batch_relaying_test.go
Labels: S:backport/v0.1.x
