Repository umee-network/peggo, pull requests merged in 2022-10, with the labels that each got.

#376 feat: Add eth merge pause flag (to main)
  .mergify.yml
  CHANGELOG.md
  cmd/peggo/flags.go
  cmd/peggo/orchestrator.go
  orchestrator/eth_event_watcher.go
  orchestrator/eth_event_watcher_test.go
  orchestrator/main_loops.go
  orchestrator/oracle_resync_test.go
  orchestrator/orchestrator.go
Labels: A:Automerge, S:backport/v1.x.x

#381 feat: improve bridge pause
  orchestrator/eth_event_watcher.go
  orchestrator/main_loops.go
Labels: S:backport/v1.x.x

#385 feat: create docker images when new tag is released
  .dockerignore
  .github/workflows/docker-release.yml
  contrib/images/Dockerfile
Labels: A:Automerge

#394 feat: add GCP logs
  README.md
  cmd/peggo/flags.go
  cmd/peggo/orchestrator.go
  go.mod
  go.sum
Labels: C:CLI, T:Dev-UX, S:backport/v1.x.x

#397 chore: update changelog
  CHANGELOG.md
Labels: A:Automerge, P:Low, S:backport/v1.x.x

#399 feat: update price feeder and umee versions
  CHANGELOG.md
  cmd/peggo/orchestrator.go
  go.mod
  go.sum
  orchestrator/oracle/oracle.go
Labels: A:Automerge, T:Dependencies, P:Low, S:backport/v1.x.x
