Repository umee-network/peggo, pull requests merged in 2022-09, with the labels that each got.

#359 fix: v1 changelogs
  CHANGELOG.md
  test/manual-test-peggo.md
Labels: T:Client-UX

#362 feat: update to umeed v3
  .github/workflows/tests.yml
  .golangci.yml
  CHANGELOG.md
  Dockerfile
  cmd/peggo/client/context.go
  cmd/peggo/flags.go
  cmd/peggo/keys.go
  go.mod
  go.sum
  test/e2e/chain.go
  test/e2e/e2e_setup_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_util_test.go
  test/e2e/orchestrator.go
  test/e2e/validator.go
Labels: A:Automerge

#365 feat: reduce oracle noise msgs
  .mergify.yml
  cmd/peggo/orchestrator.go
  orchestrator/oracle/oracle.go
  test/cosmos/multinode.sh
  test/eth/run_ganache.sh
  test/scripts/valset_update_2000_blocks.sh
Labels: S:backport/v1.0.x

#367 chore: modify eth block delay
  CHANGELOG.md
  orchestrator/main_loops.go
  orchestrator/main_loops_test.go
Labels: S:backport/v1.0.x
