Repository umee-network/peggo, pull requests merged in 2022-02, with the labels that each got.

#172 feat: Add token addresses fallback
  CHANGELOG.md
  orchestrator/coingecko/coingecko.go
  orchestrator/coingecko/coingecko_test.go
  orchestrator/coingecko/constants.go
  orchestrator/relayer/batch_relaying.go
Labels: S:backport/v0.2.x

#174 fix: Deprecate --eth-pk in favor of env var
  CHANGELOG.md
  README.md
  cmd/peggo/flags.go
  test/e2e/e2e_setup_test.go
  test/e2e/e2e_util_test.go
Labels: C:CLI, S:backport/v0.2.x

#185 feat: Add Umee address
  orchestrator/coingecko/constants.go
Labels: S:backport/v0.2.x

#189 feat: Valset relaying modes
  CHANGELOG.md
  README.md
  cmd/peggo/bridge.go
  cmd/peggo/flags.go
  cmd/peggo/orchestrator.go
  orchestrator/relayer/find_latest_valset.go
  orchestrator/relayer/main_loop.go
  orchestrator/relayer/relayer.go
  orchestrator/relayer/relayer_test.go
  orchestrator/relayer/valset_relaying.go
  test/e2e/e2e_setup_test.go
Labels: S:backport/v0.2.x

#201 chore: Add new ERC20s
  orchestrator/coingecko/constants.go
Labels: S:backport/v0.2.x

#202 chore: Remove deprecated flags (Do NOT backport)
  cmd/peggo/flags.go
  cmd/peggo/orchestrator.go
Labels: A:Automerge

#209 fix: ensure peggo version cmd works correctly
  CHANGELOG.md
  Makefile
  cmd/peggo/version.go
Labels: A:Automerge, S:backport/v0.2.x

#205 fix: warn user when using unencrypted non-local urls
  cmd/peggo/bridge.go
  cmd/peggo/flags.go
  cmd/peggo/orchestrator.go
Labels: A:Automerge, C:CLI, C:Audit

#213 chore: changelog update
  CHANGELOG.md
Labels: A:Automerge, S:backport/v0.2.x

#217 fix: Add Ethereum addresses check
  CHANGELOG.md
  cmd/peggo/bridge.go
  cmd/peggo/keys.go
  cmd/peggo/orchestrator.go
Labels: S:backport/v0.2.x

#218 chore: Clarify Ethereum gas price unit
  cmd/peggo/flags.go
Labels: S:backport/v0.2.x

#216 feat: Check profitability before requesting batches (mvp)
  CHANGELOG.md
  Dockerfile
  cmd/peggo/orchestrator.go
  orchestrator/coingecko/coingecko.go
  orchestrator/eth_event_watcher_test.go
  orchestrator/main_loops.go
  orchestrator/oracle_resync_test.go
  orchestrator/orchestrator.go
  orchestrator/relayer/batch_relaying.go
  orchestrator/relayer/relayer.go
Labels: S:backport/v0.2.x
